<?xml version="1.0" encoding="UTF-8"?>
<!-- AMA: The purpose of this XSLT is to output the an svg page that shows the variances between all editions page. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xpath-default-namespace="http://www.tei-c.org/ns/1.0"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math"
    exclude-result-prefixes="xs math"
    xmlns="http://www.w3.org/1999/xhtml"
    version="3.0">

    <xsl:output method="xml" encoding="utf-8" doctype-system="about:legacy-compat" omit-xml-declaration="yes"/>
    <xsl:variable name="currentEdition" as="node()+" select="descendant::note"/>
    <xsl:variable name="currentAB" as="node()+" select="descendant::ab"/>
    <xsl:template match="/">
        <xsl:for-each select="$currentAB">
            <xsl:result-document method="text" indent="yes" href="../analysis/ab{position()}-analysis-table.txt">
                <xsl:text>AB </xsl:text><xsl:value-of select="position()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>C </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#C'] => count()"/><xsl:text> D </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')][contains(., 'D')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>C </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#C'] => count()"/><xsl:text> I </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')][contains(., 'I')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>C </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#C'] => count()"/><xsl:text> J </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')][contains(., 'J')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>C </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#C'] => count()"/><xsl:text> O </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')][contains(., 'O')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>C </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#C'] => count()"/><xsl:text> R </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')][contains(., 'R')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>C </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#C'] => count()"/><xsl:text> S </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')][contains(., 'S')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>C </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#C'] => count()"/><xsl:text> W </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'C')][contains(., 'W')]] => count()"/><xsl:text>&#10;</xsl:text>
                
                <xsl:text>D </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#D'] => count()"/><xsl:text> C </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')][contains(., 'C')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>D </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#D'] => count()"/><xsl:text> I </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')][contains(., 'I')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>D </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#D'] => count()"/><xsl:text> J </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')][contains(., 'J')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>D </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#D'] => count()"/><xsl:text> O </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')][contains(., 'O')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>D </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#D'] => count()"/><xsl:text> R </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')][contains(., 'R')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>D </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#D'] => count()"/><xsl:text> S </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')][contains(., 'S')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>D </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#D'] => count()"/><xsl:text> W </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'D')][contains(., 'W')]] => count()"/><xsl:text>&#10;</xsl:text>
                
                <xsl:text>I </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#I'] => count()"/><xsl:text> C </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')][contains(., 'C')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>I </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#I'] => count()"/><xsl:text> D </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')][contains(., 'D')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>I </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#I'] => count()"/><xsl:text> J </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')][contains(., 'J')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>I </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#I'] => count()"/><xsl:text> O </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')][contains(., 'O')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>I </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#I'] => count()"/><xsl:text> R </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')][contains(., 'R')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>I </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#I'] => count()"/><xsl:text> S </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')][contains(., 'S')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>I </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#I'] => count()"/><xsl:text> W </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'I')][contains(., 'W')]] => count()"/><xsl:text>&#10;</xsl:text>
                
                <xsl:text>J </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#J'] => count()"/><xsl:text> C </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')][contains(., 'C')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>J </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#J'] => count()"/><xsl:text> D </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')][contains(., 'D')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>J </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#J'] => count()"/><xsl:text> I </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')][contains(., 'I')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>J </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#J'] => count()"/><xsl:text> O </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')][contains(., 'O')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>J </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#J'] => count()"/><xsl:text> R </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')][contains(., 'R')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>J </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#J'] => count()"/><xsl:text> S </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')][contains(., 'S')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>J </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#J'] => count()"/><xsl:text> W </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'J')][contains(., 'W')]] => count()"/><xsl:text>&#10;</xsl:text>
                
                <xsl:text>O </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#O'] => count()"/><xsl:text> C </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')][contains(., 'C')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>O </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#O'] => count()"/><xsl:text> D </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')][contains(., 'D')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>O </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#O'] => count()"/><xsl:text> I </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')][contains(., 'I')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>O </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#O'] => count()"/><xsl:text> J </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')][contains(., 'J')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>O </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#O'] => count()"/><xsl:text> R </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')][contains(., 'R')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>O </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#O'] => count()"/><xsl:text> S </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')][contains(., 'S')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>O </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#O'] => count()"/><xsl:text> W </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'O')][contains(., 'W')]] => count()"/><xsl:text>&#10;</xsl:text>
                
                <xsl:text>R </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#R'] => count()"/><xsl:text> C </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')][contains(., 'C')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>R </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#R'] => count()"/><xsl:text> D </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')][contains(., 'D')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>R </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#R'] => count()"/><xsl:text> I </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')][contains(., 'I')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>R </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#R'] => count()"/><xsl:text> J </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')][contains(., 'J')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>R </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#R'] => count()"/><xsl:text> O </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')][contains(., 'O')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>R </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#R'] => count()"/><xsl:text> S </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')][contains(., 'S')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>R </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#R'] => count()"/><xsl:text> W </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'R')][contains(., 'W')]] => count()"/><xsl:text>&#10;</xsl:text>
                
                <xsl:text>S </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#S'] => count()"/><xsl:text> C </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')][contains(., 'C')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>S </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#S'] => count()"/><xsl:text> D </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')][contains(., 'D')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>S </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#S'] => count()"/><xsl:text> I </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')][contains(., 'I')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>S </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#S'] => count()"/><xsl:text> J </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')][contains(., 'J')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>S </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#S'] => count()"/><xsl:text> O </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')][contains(., 'O')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>S </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#S'] => count()"/><xsl:text> R </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')][contains(., 'R')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>S </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#S'] => count()"/><xsl:text> W </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'S')][contains(., 'W')]] => count()"/><xsl:text>&#10;</xsl:text>
                
                <xsl:text>W </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#W'] => count()"/><xsl:text> C </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')][contains(., 'C')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>W </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#W'] => count()"/><xsl:text> D </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')][contains(., 'D')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>W </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#W'] => count()"/><xsl:text> I </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')][contains(., 'I')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>W </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#W'] => count()"/><xsl:text> J </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')][contains(., 'J')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>W </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#W'] => count()"/><xsl:text> O </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')][contains(., 'O')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>W </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#W'] => count()"/><xsl:text> R </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')][contains(., 'R')]] => count()"/><xsl:text>&#10;</xsl:text>
                <xsl:text>W </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')]] => count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')]][not(descendant::text())] =>count()"/><xsl:text> </xsl:text><xsl:value-of select=".[position()]//rdg[@wit='#W'] => count()"/><xsl:text> S </xsl:text><xsl:value-of select=".[position()]//rdg[@wit[contains(., 'W')][contains(., 'S')]] => count()"/><xsl:text>&#10;</xsl:text>
                
                <xsl:text>&#10;</xsl:text>
            </xsl:result-document>
        </xsl:for-each>
    </xsl:template>

</xsl:stylesheet>